UNIFI_DEFAULT_HOST = "unifi"
UNIFI_DEFAULT_PORT = 443
UNIFI_DEFAULT_USERNAME = "admin"
UNIFI_DEFAULT_PASSWORD = "ubnt"
UNIFI_DEFAULT_SITE = "default"

MQTT_DEFAULT_TOPIC = "unifi"
MQTT_DEFAULT_PORT = 1883
