UNIFI_DEFAULT_HOST = "unifi"
UNIFI_DEFAULT_PORT = 443
UNIFI_DEFAULT_USERNAME = "admin"
UNIFI_DEFAULT_PASSWORD = "ubnt"
UNIFI_DEFAULT_SITE = "default"

MQTT_DEFAULT_HOST = "localhost"
MQTT_DEFAULT_PORT = 1883
MQTT_DEFAULT_NAME = "unifi"
MQTT_DEFAULT_USERNAME = "mqtt"
MQTT_DEFAULT_PASSWORD = "mqtt"
